repos:
    # General file checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
          args: ['--maxkb=1000']
        - id: check-json
        - id: check-merge-conflict
        - id: detect-private-key
        - id: mixed-line-ending

    # Secret scanning
    - repo: https://github.com/trufflesecurity/trufflehog
      rev: v3.63.2
      hooks:
        - id: trufflehog
          name: TruffleHog
          entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
          language: system
          stages: [commit]

    # Terraform formatting, validation, and security scanning
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.83.6
      hooks:
        - id: terraform_fmt
        - id: terraform_validate
        - id: terraform_tflint
          args:
            - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - id: terraform_tfsec
          args:
            - --args=--soft-fail
            - --args=--format=default
        - id: terraform_docs
          args:
            - --args=--output-file=README.md
            - --args=--output-mode=inject
            - --args=--markdown-table-indent=2

    # Markdown linting
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.38.0
      hooks:
        - id: markdownlint
          args: ['--fix']
