name: 'Terraform CI'

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  job_id:
    runs-on: ubuntu-latest
    name: Terraform
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Authenticate to Google Cloud via Workload Identity Federation'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/changeme-project/locations/global/workloadIdentityPools/workload-pool-github/providers/my-provider'
        service_account: 'sacct-changeme'
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
